### ISSUE TITLE
Secrets Management Overhaul

### ISSUE THREAD

**Issue by ghost** [grafeas/voucher#16]
Our secrets management system currently relies on ejson, but although Shopify uses ejson there are many different secrets management systems out there!

Thus we should add support for:

- [ ] Google Secrets Manager
- [ ] HashiCorp Vault

This will require refactoring the logic in `cmd/config` as well as the `server` and `subscriber` packages.

**Comment by thepwagner** [comment]
Related: we're proposing https://github.com/mozilla/sops as an alternative backend, which allows GCP-KMS, AWS-KMS, GPG, Vault, etc over in https://github.com/grafeas/voucher/pull/35 

I think that PR closes this issue.
