### ISSUE TITLE
make the go get compatible with go modules

### ISSUE THREAD

**Issue by Nilay-Shah** [grafeas/voucher#19]
right now if one types out `go get github.com/grafeas/voucher` it will get `v1.2.2` of Voucher. this is because it's the latest `v1` version of Voucher and since we're using go modules, we need to adopt a new module path to be able to make `go get` correctly fetch the latest version (and also any other `v2` version; `v2.5.3` is the latest version). more information about this can be found in [this official blog post](https://blog.golang.org/module-compatibility)

for now though, if one wants to fetch any `v2` version of this package they have to reference it by commit hash. for example:
```
➜ go get github.com/grafeas/voucher@fef6b9c35e24e71ba48804ed96a3e4117da95e91
go: github.com/grafeas/voucher fef6b9c35e24e71ba48804ed96a3e4117da95e91 => v1.2.3-0.20210303185942-fef6b9c35e24
go: downloading github.com/grafeas/voucher v1.2.3-0.20210303185942-fef6b9c35e24
```

**Comment by ooq** [comment]
Technically, does this have be to be updated for every `v2` version released?

**Comment by catherinejones** [comment]
> Technically, does this have be to be updated for every `v2` version released?

Nope! Once the "v2" directory exists go mod will download the latest tag as it's compatible. We will have to make a "v3" directory when we bump the major version however!
