### ISSUE TITLE
add a voucher_subscriber option

### ISSUE THREAD

**Issue by Nilay-Shah** [grafeas/voucher#9]
introduce a third option to run Voucher: `voucher_subscriber`. this should implement the existing `Server` interface to allow us to hook into a GCP pub/sub topic to vouch images automatically. since there is already [a topic to subscribe to for GCR images](https://cloud.google.com/container-registry/docs/configuring-notifications), this allows us to run Voucher and automatically vouch all images pushed to GCR. 
the `project` and `subscription` will be passed in as command line arguments (ie. `voucher_subscriber  --project=my-cool-project --subscription=all-gcr-images`

cc: @ooq @cjones-shopify

**Comment by ook** [comment]
Interesting typo ping. And interesting project. Have fun 👍 ;)
